### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [yandex/fastops#11]
Hi!

Thank you for the such cool library! I'm interested in packaging the library into some dependecy managers. It will be much easier if you make a release on GitHub, so in a package recipe I will rely on some "stable" version instead of specific commit. E.g. it much easier to create a package for Conan with release.

Thank you!

**Comment by danlark1** [comment]
Hi!

Thanks.

I am not an expert in the github releases, what would be the best option for the release? Just to provide the source code in an archive or also pre-build shared/static library?

**Comment by ZaMaZaN4iK** [comment]
That's up to you :) From my side - source code is enough since C and C++ developers like to customize build options and don't really trust to something prebuilt. Also releasing only source code will be easier for you.

Also, please use semver for versioning - it makes life a lot easier :)

**Comment by danlark1** [comment]
Sorry that it took so long to push two buttons, I forgot about it.

v1.0.0 is released :)
