### ISSUE TITLE
AVX2 detection is broken

### ISSUE THREAD

**Issue by danfe** [yandex/fastops#14]
Right now, AVX2 is detected by examining EBX register after calling Function 7 of CPU identification.  However, it requires passing subfunction zero as well, so simple `__cpuid()` call is not sufficient, you should (must?) call `__cpuidex()` on Windows and `__cpuid_count()` elsewhere.

**Comment by nemo-cpt** [comment]
Thank you, I am testing the change proposed by you.

**Comment by nemo-cpt** [comment]
Fix has landed, please recheck.

**Comment by danfe** [comment]
Looks correct, thanks.  Personally I've made it an argument (if you don't want to touch existing calls, move it to the right and assign default value of zero), but that's more of a matter of taste I guess.
